git_repo_url: "https://github.com/0x464e/homelab.git"

traefik_repo: "traefik/traefik"
traefik_folder: "/etc/traefik"
traefik_bin_path: "/usr/bin/traefik"

domain: "ottos.party"
domain_regex: '^.*\.ottos\.party(.*)$'

cf_email: "email"
cloudflare_dns_api_token: "token"

tos_repo: "0x464e/traefik-opnsense-sync"
tos_folder: "/etc/traefik-opnsense-sync"
tos_bin_path: "/usr/bin/traefik-opnsense-sync"

opnsense_api_key: "key"
opnsense_api_secret: "secret"

proxmox_server_address: "192.168.10.4:8006"
proxmox_router_address: "192.168.10.3:8006"
opnsense_address: "192.168.10.1"
home_assistant_address: "192.168.10.7:8123"
adguard_home_address: "192.168.10.8"
truenas_address: "192.168.10.5"
openwrt_address: "192.168.10.2"
smlight_address: "192.168.20.10"
