services:
  whoami:
    image: traefik/whoami
    container_name: whoami

    ports:
      - "192.168.10.6:6767:80"

    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.ottos.party`)"
      - "traefik.http.routers.whoami.entrypoints=lan-https,cf-tunnel"
      - "traefik.http.routers.whoami.middlewares=cloudflarewarp@file, authentik-forward-auth@file, proxy-secret@file"
