services:
  copyparty:
    image: copyparty/dj:latest
    container_name: copyparty
    user: "1000:1000"
    ports:
      - "192.168.10.6:3923:3923"
    volumes:
      - /srv/copyparty:/cfg:z
      - /mnt/share:/w:z

    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)

      PYTHONUNBUFFERED: 1
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)

    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

    restart: unless-stopped

    labels:
      - "traefik.enable=true"

      # main route
      - "traefik.http.routers.copyparty.rule=Host(`files.ottos.party`)"
      - "traefik.http.routers.copyparty.entrypoints=lan-https,cf-tunnel"
      - "traefik.http.routers.copyparty.middlewares=cloudflarewarp@file"

      # aliases route
      - "traefik.http.routers.copyparty-aliases.rule=Host(`copyparty.ottos.party`)"
      - "traefik.http.routers.copyparty-aliases.entrypoints=lan-https,cf-tunnel"
      - "traefik.http.routers.copyparty-aliases.middlewares=cloudflarewarp@file,copyparty-alias-redirect"
      - "traefik.http.routers.copyparty-aliases.service=noop@internal"

      # alias redirect middleware
      - "traefik.http.middlewares.copyparty-alias-redirect.redirectregex.regex=^.*\\.ottos\\.party(.*)$"
      - "traefik.http.middlewares.copyparty-alias-redirect.redirectregex.replacement=https://files.ottos.party$1"
      - "traefik.http.middlewares.copyparty-alias-redirect.redirectregex.permanent=true"
