services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "256mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/config:/config
      - /srv/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971" # API and web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${RTSP_PASSWORD}
    labels:
      - "traefik.enable=true"

      # main route
      - "traefik.http.routers.frigate.rule=Host(`frigate.ottos.party`)"
      - "traefik.http.routers.frigate.entrypoints=lan-https"

      # aliases route
      - "traefik.http.routers.frigate-aliases.rule=Host(`nvr.ottos.party`)"
      - "traefik.http.routers.frigate-aliases.entrypoints=lan-https"
      - "traefik.http.routers.frigate-aliases.middlewares=frigate-alias-redirect"
      - "traefik.http.routers.frigate-aliases.service=noop@internal"

      # alias redirect middleware
      - "traefik.http.middlewares.frigate-alias-redirect.redirectregex.regex=^.*\\.ottos\\.party(.*)$"
      - "traefik.http.middlewares.frigate-alias-redirect.redirectregex.replacement=https://frigate.ottos.party$1"
      - "traefik.http.middlewares.frigate-alias-redirect.redirectregex.permanent=true"
