name: observability

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: 1000:1000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ENABLE_GZIP=true
      - GF_DATE_FORMATS_INTERVAL_HOUR=Do MMM HH:mm
      - GF_DATE_FORMATS_INTERVAL_DAY=Do MMM
      - GF_DATE_FORMATS_INTERVAL_MONTH=MMM YYYY
      - GF_AUTH_ANONYMOUS_ORG_NAME=Homelab
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "192.168.10.6:3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.ottos.party`)"
      - "traefik.http.routers.grafana.entrypoints=lan-https"

  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET_NAME}
    volumes:
      - /srv/influxdb/data:/var/lib/influxdb2
      - /srv/influxdb/config:/etc/influxdb2
    ports:
      - "192.168.10.6:8086:8086"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.ottos.party`)"
      - "traefik.http.routers.influxdb.entrypoints=lan-https"
